// Generated by https://quicktype.io

import { ApiProperty } from '@nestjs/swagger';

export class Profile {
  @ApiProperty()
  _id?: string;
  @ApiProperty()
  isActive: boolean;
  @ApiProperty()
  name: string;
  @ApiProperty()
  services: Service[];
  @ApiProperty()
  createdAt: Date;
  @ApiProperty()
  updatedAt: Date;
}

export class Service {
  @ApiProperty()
  name: string;
  @ApiProperty()
  isEnabled: boolean;
}
